---
  - name: Tasks for remaining prereq on all the hosts
    hosts: master
    become: yes
    become_user: root
    tasks:
      - name: Disable SELinux
        selinux:
          state: disabled

      - name: Set swappiness to 1
        lineinfile:
          backup=yes
          state=present
          dest=/etc/sysctl.conf
          regexp='^#?vm.swappiness'
          line='vm.swappiness=1'

      - name: Set swappiness to 1
        shell: sysctl -p

      - name: update hugepage value for enabled
        shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled

      - name: update hugepage value for defrag
        shell: echo never > /sys/kernel/mm/transparent_hugepage/defrag

      - name: update hugepage value for enabled for reboot
        lineinfile:
          backup=yes
          state=present
          dest=/etc/rc.d/rc.local
          regexp='^#?transparent_hugepage/enabled'
          line='echo never > /sys/kernel/mm/transparent_hugepage/enabled'

      - name: update hugepage value for defrag for reboot
        lineinfile:
          backup=yes
          state=present
          dest=/etc/rc.d/rc.local
          regexp='^#?transparent_hugepage/defrag'
          line='echo never > /sys/kernel/mm/transparent_hugepage/defrag'

      - name: update rc.local to disable ipv6 - 1
        shell: sysctl -w net.ipv6.conf.all.disable_ipv6=1

      - name: update rc.local to disable ipv6 - 2
        shell: sysctl -w net.ipv6.conf.default.disable_ipv6=1

      - name: update rc.local to disable ipv6 - 3
        shell: sysctl -w net.ipv6.conf.lo.disable_ipv6=0

      - name: update rc.local to disable ipv6 - 1
        lineinfile:
          backup=yes
          state=present
          dest=/etc/rc.d/rc.local
          regexp='^#?net.ipv6.conf.all.disable_ipv6'
          line='sysctl -w net.ipv6.conf.all.disable_ipv6=1'

      - name: update rc.local to disable ipv6 - 2
        lineinfile:
          backup=yes
          state=present
          dest=/etc/rc.d/rc.local
          regexp='^#?net.ipv6.conf.default.disable_ipv6'
          line='sysctl -w net.ipv6.conf.default.disable_ipv6=1'

      - name: update rc.local to disable ipv6 - 3
        lineinfile:
          backup=yes
          state=present
          dest=/etc/rc.d/rc.local
          regexp='^#?net.ipv6.conf.lo.disable_ipv6'
          line='sysctl -w net.ipv6.conf.lo.disable_ipv6=0'

      - name: Add execute permission to /etc/rc.d/rc.local
        file:
          dest: /etc/rc.d/rc.local
          mode: a+x

      - name: install packages
        yum:
          name:
           - ipa-client
           - wget
           - ntp
           - git

      - name: Stop chronyd since running ntpd
        ansible.builtin.service:
          name: chronyd
          state: stopped
          enabled: false
        ignore_errors: true

      - name: Enable and run ntpd
        ansible.builtin.service:
          name: ntpd
          enabled: true          
          state: restarted

      - name: Stop firewalld
        ansible.builtin.service:
          name: firewalld
          state: stopped
          enabled: false
        ignore_errors: true