= Single Node CDP Base Cluster setup on Virtualized Infrastructure
:toc:

===== Single Node CDP Base Cluster

[frame=all, grid=all]
|===
|Virtual Machine Size           | CDP Role         | Storage

| 16vcpu/128G(Minimum) 

  32vcpu/128G(Recommended)     | CDP Base Cluster | 200 GB Root(OS) volume 
|===


* SSH into the pvcbasemaster node, switch to root user, and run the below commands. 

[,shell]
----
sudo su - root
yum install git -y
mkdir -p /tmp/CDP_PvC/Logs
git clone https://github.com/pannagk/Single_Node_CDP_Base_Cluster.git /tmp/CDP_PvC/Single_Node_CDP_Base_Cluster
----

* Navigate to the /tmp/CDP_PvC/Single_Node_CDP_Base_Cluster folder and run the next set of commands as shwon below. 

[,shell]
----
cd /tmp/CDP_PvC/Single_Node_CDP_Base_Cluster
chmod +x *.sh
nohup sh 0_base_master_pre_setup.sh > /tmp/CDP_PvC/Logs/0_base_master_pre_setup.log &
----

* After running the *nohup* command, check the logs with the below command. You should see the output as *Pre-Setup completed*. 

[,shell]
----
tail -f -n +1 /tmp/CDP_PvC/Logs/0_base_master_pre_setup.log
----

* In this step, we will run through the CDP Base OS Prerequisites such as password less ssh from the master, disabling SELinux, disabling IPv6 etc.., 

* Login to the *master* node, switch to the root user, and navigate to the directory */tmp/CDP_PvC/Single_Node_CDP_Base_Cluster*, and the script *1_CDP_Base_OS_Prereq.sh*. 

[,shell]
----
sudo su - root
cd /tmp/CDP_PvC/Single_Node_CDP_Base_Cluster
nohup sh 1_CDP_Base_OS_Prereq.sh > /tmp/CDP_PvC/Logs/1_CDP_base_OS_prereq.log &
----

* After running the above *nohup* command, check the logs with the below command. 

[,shell]
----
tail -f -n +1 /tmp/CDP_PvC/Logs/1_CDP_base_OS_prereq.log
----

* In order to disable SELinux, the master node needs to be rebooted. Run the below command and wait for some time before logging into it. 
[,shell]
----
reboot
----

* Wait for 1 or 2 minutes, and then log back into the base master. Switch to root user and run the verify_CDP_base_prereq.sh script. 
[,shell]
----
sudo su -root
cd /tmp/CDP_PvC/Single_Node_CDP_Base_Cluster
nohup sh 2_verify_CDP_base_prereq.sh > /tmp/CDP_PvC/Logs/2_verify_CDP_base_prereq.log &
----

* After running the above *nohup* command, check the logs with the below command. 

[,shell]
----
tail -f -n +1 /tmp/CDP_PvC/Logs/2_verify_CDP_base_prereq.log &
----

* You should see the values for different parameters as below. 
[,shell]
----
"ansible_facts.selinux.status": "disabled"

"swappiness_status.stdout_lines": [
    "vm.swappiness = 1"]

"enabled_hugepage_value.stdout_lines": [
    "always madvise [never]"]

"defrag_hugepage_value.stdout_lines": [
    "always madvise [never]"]

"ntpd_status.status.ActiveState": "active"

"ntpd_enabled_status.stdout_lines": [
    "enabled"]

"firewalld_status.status.ActiveState": "inactive"   

"rc_local_status.stdout_lines": [
    "#!/bin/bash",
    "# THIS FILE IS ADDED FOR COMPATIBILITY PURPOSES",
    "#",
    "# It is highly advisable to create own systemd services or udev rules",
    "# to run scripts during boot instead of using this file.",
    "#",
    "# In contrast to previous versions due to parallel execution during boot",
    "# this script will NOT be run after all other services.",
    "#",
    "# Please note that you must run 'chmod +x /etc/rc.d/rc.local' to ensure",
    "# that this script will be executed during boot.",
    "",
    "touch /var/lock/subsys/local",
    "echo never > /sys/kernel/mm/transparent_hugepage/enabled",
    "echo never > /sys/kernel/mm/transparent_hugepage/defrag",
    "sysctl -w net.ipv6.conf.all.disable_ipv6=1",
    "sysctl -w net.ipv6.conf.default.disable_ipv6=1",
    "sysctl -w net.ipv6.conf.lo.disable_ipv6=0"]

----
 
* Once you see the CDP Base Prequisites completion message, you can exit from the log tailing. Press *ctrl+c* or *ctrl+z*. 
